### ISSUE TITLE
Running gha-auto-tag manually will set v1 to the default branch, instead of correct minor branch

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-auto-tag#13]
https://github.com/silverstripe/gha-merge-up/actions/runs/5995013597

![image](https://github.com/silverstripe/gha-merge-up/assets/4809037/d129fa27-ccaf-45a6-a5bb-df5195286cee)

![image](https://github.com/silverstripe/gha-merge-up/assets/4809037/3969e4e2-a70f-4674-911a-97ccf1bb8123)

## PRs
- https://github.com/silverstripe/gha-auto-tag/pull/14

**Comment by emteknetnz** [comment]
Can't fix - see https://github.com/silverstripe/gha-tag-release/#why-there-is-no-sha-input-paramater

I suppose given auto tag is only meant to be used in the context of github actions, this probably isn't too bad of an issue

As long as we fix https://github.com/silverstripe/gha-tag-release/issues/21 then this shouldn't be an issue at all in practice

**Comment by emteknetnz** [comment]
Actually real issue here is that it's using the latest commit of `1`, instead of `1.0`.  Given that it hasn't been merged-up it means it's releasing v1 against old stuff

**Comment by ChloeSartorelli** [comment]
PR merged
